# Programa Ingenias+ Data Science

Como dijimos en clases anteriores, Python tiene implementadas muchas librerias para poder trabajar con datos. En la clase de hoy trabajaremos con una de ellas: `Numpy`.

Antes de comenzar, vamos a hablar un poco de esta libreria o modulo.

**Numpy** es una librería optimizada para realizar cálculos numéricos con vectores y matrices. A diferencia de otros lenguajes de programación, Python no posee en su estructura central la figura de matrices. Eso quiere decir que para poder trabajar con esta estructura de datos deberiamos trabajar con listas de listas. NumPy introduce el concepto de arrays o matrices.

Al ser de código abierto, `numpy` posee una documentación muy amplia que es **SIEMPRE RECOMENDABLE** consultar.

- [Documentacion NumPy](https://devdocs.io/numpy/)

## Clase 4: Introduccion a NumPy

# Ejercicios

1. Crear un arreglo de ceros de longitud 12
2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
3. Crear un arreglo que tenga los números del 10 al 49
4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
6. Calcular la media de un arreglo usando np.sum
7. Calcular la varianza de un arreglo usando np.sum y np.mean
8. Crear un array de números aleatorios usando np.random.randn.


In [2]:
import numpy as np

1. Crear un arreglo de ceros de longitud 12

In [4]:
arreglo_ceros = np.zeros(12)

print(arreglo_ceros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5.

In [8]:
arreglo_unos = np.zeros(10)
arreglo_unos[4] = 10 # se cmabia el valor de pa posición 5 a 10

print(arreglo_unos)

[ 0.  0.  0.  0. 10.  0.  0.  0.  0.  0.]


3. Crear un arreglo que tenga los números del 10 al 49

In [9]:
arreglo_numeros = np.arange(10,50)
arreglo_numeros

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Crear un arreglo 2d de shape (3,3) que tenga los números del 0 al 8.

In [10]:
arreglo_2d = np.arange(0, 9).reshape(3, 3)

print(arreglo_2d)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza

In [13]:
arreglo_num_aleatorios = np.random.rand(100) # creo un arreglo con 100 números cualesquiera

In [18]:
media = np.mean(arreglo_num_aleatorios) # media del arreglo de 100 números
media

0.5153045490571745

In [23]:
arreglo_num_aleatorios.mean() # otra manera

0.5153045490571745

In [22]:
varianza = np.var(arreglo_num_aleatorios) # varianza de arreglo de 100 numeros.
varianza

0.08624383745677555

In [24]:
arreglo_num_aleatorios.var() #otra manera

0.08624383745677555

6. Calcular la media de un arreglo usando np.sum

In [26]:
arreglo_media = np.sum(arreglo_numeros)/len(arreglo_numeros)
arreglo_media

29.5

7. Calcular la varianza de un arreglo usando np.sum y np.mean

In [37]:
media = np.mean(arreglo_numeros) # calculo la media del arreglo
dif_cuadrado = (arreglo_numeros - media)**2 # diferencia de cuadrados
sum_dif2 = np.sum(dif_cuadrado) # suma de las diferencias de cuadrado
var = sum_dif2 / (len(arreglo_numeros) - 1) #calculo de varianza
var


136.66666666666666

8. Crear un array de números aleatorios usando np.random.randn

In [41]:
arreglo_nuevo = np.random.randn(10)
arreglo_nuevo


array([ 0.00277994,  1.53760931, -0.68619549,  1.13136284, -0.09382604,
       -0.3397732 ,  0.72591827,  0.56121529, -0.52642842, -0.57506719])